### ISSUE TITLE
Work plan for v0.0.1.alpha.2

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-annotation-extension#28]
_Following up on [v0.0.0-alpha.1](https://github.com/mapbox/map-extensions-ios/issues/8)_.

## Functionality improvements
- [ ] Add swift names
- [x] Research how to add a drag gesture to the annotations (@fabian-guerra)
- [ ] Evaluate how to create a controller from a geoJSON file (@fabian-guerra) 

## Documentation
- [x] Complete API documentation (@captainbarbosa - https://github.com/mapbox/map-extensions-ios/pull/29)
- [x] Set up iOS documentation landing page (@captainbarbosa)
- [x] Improve demo app (@captainbarbosa - https://github.com/mapbox/map-extensions-ios/pull/30)

## Testing
- [ ] Expand test coverage (@captainbarbosa)
- [ ] Integration. The integration tests will consist in adding one controller type to the map with the user interaction enabled.
- [ ] Performance. Take a look at https://www.raywenderlich.com/4065-practical-instruments use the time and memory profilers. Generate 100, 1000, 10000 annotations. See the example in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/app/MBXViewController.m#L818-L857

## Automation
- [ ] Auto-generate annotations.
- [ ] Auto-generate controllers.
- [ ] Auto-generate data conversion objects.
- [ ] Auto-generate unit tests.

**Comment by captainbarbosa** [comment]
Beta’s our, let move this to another ticket.
