### ISSUE TITLE
Mapbox iOS Annotation Extension renaming

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-annotation-extension#31]
From the last annotations sync with @zugaldia @captainbarbosa, we discussed consistent naming conventions:

### Proposed Guidelines
- Call plugins **"Extensions"** on iOS, not "Framework Extensions." 
- Call our first extension the **"Annotation Extension"**, with "annotation" being singular ~plural, to avoid having to rename the podspec~
- Call this repo **"mapbox-extensions-ios"** to keep parity with Android's [mapbox-plugins-android](https://github.com/mapbox/mapbox-plugins-android) and to allow for the possibility that future non-maps extensions can be housed in this repo, e.g. geocoder plugins

cc @fabian-guerra @mapbox/ios -- any feedback on the above? Deadline: 5pm Pacific time on July 23.

### To-Do
- [ ] Rename map-extensions-ios repo to mapbox-extensions-ios
- [ ] All instances of "framework" in the context of "framework extensions" should be deleted 
  - [ ] update https://github.com/mapbox/map-extensions-ios readme.md
  - [ ] change https://github.com/mapbox/map-extensions-ios repo description to: "Mapbox extensions that can be used to augment the Mapbox Maps SDK for iOS."
  - [ ] change https://github.com/mapbox/map-extensions-ios/tree/master/annotations-framework-extension folder name
- [ ] All instances of "annotations extension" in reference to the plugin name should be renamed "annotation extension"
  - [ ] update https://github.com/mapbox/map-extensions-ios/tree/master/annotations-framework-extension readme.md 
  - [ ] ~rename [/annotationapp](https://github.com/mapbox/map-extensions-ios/tree/master/annotations-framework-extension/annotationapp), [/annotationappTests](https://github.com/mapbox/map-extensions-ios/tree/master/annotations-framework-extension/annotationappTests), and [annotationappTests.swift](https://github.com/mapbox/map-extensions-ios/blob/master/annotations-framework-extension/annotationappTests/annotationappTests.swift) folders/files with the plural "annotations" (optional -- not worth changing if it's difficult)~
- [ ] Make sure [documentation](https://github.com/mapbox/map-extensions-ios/tree/master/annotations-framework-extension/documentation) is updated to reflect these guidelines
