### ISSUE TITLE
Work plan for v0.0.1-alpha.1

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-annotation-extension#8]
This ticket tracks the work progress for releasing Mapbox's annotation framework extension.

## Initial tasks

- [x] Project setup. https://github.com/mapbox/map-extensions-ios/pull/1, https://github.com/mapbox/map-extensions-ios/pull/7, https://github.com/mapbox/map-extensions-ios/pull/10
- [x] Documentation setup. https://github.com/mapbox/map-extensions-ios/pull/2
- [x] Test app setup.

## Development tasks

- [x] API skeleton creation. https://github.com/mapbox/map-extensions-ios/pull/4, https://github.com/mapbox/map-extensions-ios/pull/6, https://github.com/mapbox/map-extensions-ios/pull/5, https://github.com/mapbox/map-extensions-ios/pull/12
- [x] Touch interaction (The ability to display callouts). https://github.com/mapbox/map-extensions-ios/pull/16
- [x] Circle based annotations. 
  - [x] Controller implementation. https://github.com/mapbox/map-extensions-ios/pull/9
  - [x] Annotation implementation. https://github.com/mapbox/map-extensions-ios/pull/9
  - [x] Data conversion classes. https://github.com/mapbox/map-extensions-ios/pull/11
  - [x] Unit test https://github.com/mapbox/map-extensions-ios/pull/21.
- [x] Symbol annotation. 
  - [x] Controller implementation. https://github.com/mapbox/map-extensions-ios/pull/18 
  - [x] Annotation implementation. https://github.com/mapbox/map-extensions-ios/pull/18 
  - [x] Data conversion classes. https://github.com/mapbox/map-extensions-ios/pull/18 
  - [x] Unit test. https://github.com/mapbox/map-extensions-ios/pull/21.
- [x] Line annotation 
  - [x] Controller implementation. https://github.com/mapbox/map-extensions-ios/pull/17
  - [x] Annotation implementation. 
  - [x] Data conversion classes. https://github.com/mapbox/map-extensions-ios/pull/17
  - [x] Unit test. https://github.com/mapbox/map-extensions-ios/pull/21.
- [x] Polygon annotation
  - [x] Controller implementation. https://github.com/mapbox/map-extensions-ios/pull/14
  - [x] Annotation implementation. **Done by @captainbarbosa https://github.com/mapbox/map-extensions-ios/pull/14**
  - [x] Data conversion classes. https://github.com/mapbox/map-extensions-ios/pull/14
  - [x] Unit test. https://github.com/mapbox/map-extensions-ios/pull/21.

## Documentation tasks
- [x] Add README.md https://github.com/mapbox/map-extensions-ios/pull/25/

## Deploy tasks

- [x] Cocoapods integration.
- [ ] Carthage integration.
- [x] CI integration

/cc @chloekraw @zugaldia
